//
GET http://localhost:3000/todos/?status=TO%20DO&priority=HIGH&priority=HIGH&status=IN%20PROGRESS 

###

//2 http requrst for Returns a specific todo based on the todo ID 
//GET http://localhost:3000/todos/:todoId/